In [9]:
import pandas as pd
from glob import glob
import openpyxl

# 請求書のExcelファイルの集約

In [5]:
# sourceフォルダのExcelファイル名を抜き出す
filepaths = glob('source/*xlsx')
filepaths

['source/請求書_10月_TTTInc.xlsx',
 'source/請求書_11月_XYZ株式会社.xlsx',
 'source/請求書_12月_株式会社ABC.xlsx']

## まず一つのファイルを読み込んでいく

In [13]:
# まず一つのファイルで読み込んでいく

filepath = filepaths[0]
_df = pd.read_excel(filepath)

In [14]:
_df

,請求書,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TTT Inc.,NaN,NaN,NaN,NaN,御中,NaN,NaN,NaN,NaN,NaN,伝票No.：,012,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,発行日：,2020/10/31,NaN,NaN,NaN,NaN,NaN,0.1
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,担当者名：,岸辺,2.0,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,税込み金額,NaN,NaN,59950.0,NaN,NaN,NaN,（税込）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,下記の通り、ご請求申し上げます。,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,No.,日付,商品コード,NaN,品名,NaN,NaN,備考,NaN,NaN,数量[L] or [-],単価[¥/L] or [¥],NaN,NaN,金額,NaN,NaN,NaN,NaN
11,1,2020-10-04 00:00:00,GSL0001,NaN,レギュラー,NaN,NaN,NaN,NaN,NaN,20,120,NaN,NaN,2400,NaN,NaN,NaN,NaN
12,2,2020-10-05 00:00:00,GSL0002,NaN,ハイオク,NaN,NaN,NaN,NaN,NaN,45,160,NaN,NaN,7200,NaN,NaN,NaN,NaN
13,3,2020-10-06 00:00:00,GSL0003,NaN,軽油,NaN,NaN,NaN,NaN,NaN,50,100,NaN,NaN,5000,NaN,NaN,NaN,NaN
14,4,2020-10-07 00:00:00,GSL0002,NaN,ハイオク,NaN,NaN,NaN,NaN,NaN,45,160,NaN,NaN,7200,NaN,NaN,NaN,NaN
15,5,2020-10-08 00:00:00,GSL0003,NaN,軽油,NaN,NaN,NaN,NaN,NaN,50,100,NaN,NaN,5000,NaN,NaN,NaN,NaN
16,6,2020-10-09 00:00:00,CMT0002,NaN,洗車 B,NaN,NaN,NaN,NaN,NaN,1,1500,NaN,NaN,1500,NaN,NaN,NaN,NaN
17,7,2020-10-10 00:00:00,GSL0003,NaN,軽油,NaN,NaN,NaN,NaN,NaN,50,100,NaN,NaN,5000,NaN,NaN,NaN,NaN
18,8,2020-10-11 00:00:00,GSL0002,NaN,ハイオク,NaN,NaN,NaN,NaN,NaN,40,160,NaN,NaN,6400,NaN,NaN,NaN,NaN
19,9,2020-10-12 00:00:00,GSL0002,NaN,ハイオク,NaN,NaN,NaN,NaN,NaN,30,160,NaN,NaN,4800,NaN,NaN,NaN,NaN
20,10,2020-10-13 00:00:00,GSL0003,NaN,軽油,NaN,NaN,NaN,NaN,NaN,50,100,NaN,NaN,5000,NaN,NaN,NaN,NaN
21,11,2020-10-14 00:00:00,GSL0003,NaN,軽油,NaN,NaN,NaN,NaN,NaN,50,100,NaN,NaN,5000,NaN,NaN,NaN,NaN
22,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,小計(税抜),NaN,54500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,消費税(10%),NaN,5450,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,合計金額(税込),NaN,59950,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## メインデータの抽出

In [15]:
_df.iloc[10]

請求書                       No.
Unnamed: 1                 日付
Unnamed: 2              商品コード
Unnamed: 3                NaN
Unnamed: 4                 品名
Unnamed: 5                NaN
Unnamed: 6                NaN
Unnamed: 7                 備考
Unnamed: 8                NaN
Unnamed: 9                NaN
Unnamed: 10      数量[L] or [-]
Unnamed: 11    単価[¥/L] or [¥]
Unnamed: 12               NaN
Unnamed: 13               NaN
Unnamed: 14                金額
Unnamed: 15               NaN
Unnamed: 16               NaN
Unnamed: 17               NaN
Unnamed: 18               NaN
Name: 10, dtype: object

In [17]:
# メインデータの抽出
columns = _df.iloc[10, [1, 2, 4, 10, 11, 14]]
columns

Unnamed: 1                 日付
Unnamed: 2              商品コード
Unnamed: 4                 品名
Unnamed: 10      数量[L] or [-]
Unnamed: 11    単価[¥/L] or [¥]
Unnamed: 14                金額
Name: 10, dtype: object

In [22]:
df = _df.iloc[11:23, [1, 2, 4, 10, 11, 14]]
df.columns = columns
df

10                   日付    商品コード     品名 数量[L] or [-] 単価[¥/L] or [¥]    金額
11  2020-10-04 00:00:00  GSL0001  レギュラー           20            120  2400
12  2020-10-05 00:00:00  GSL0002   ハイオク           45            160  7200
13  2020-10-06 00:00:00  GSL0003     軽油           50            100  5000
14  2020-10-07 00:00:00  GSL0002   ハイオク           45            160  7200
15  2020-10-08 00:00:00  GSL0003     軽油           50            100  5000
16  2020-10-09 00:00:00  CMT0002   洗車 B            1           1500  1500
17  2020-10-10 00:00:00  GSL0003     軽油           50            100  5000
18  2020-10-11 00:00:00  GSL0002   ハイオク           40            160  6400
19  2020-10-12 00:00:00  GSL0002   ハイオク           30            160  4800
20  2020-10-13 00:00:00  GSL0003     軽油           50            100  5000
21  2020-10-14 00:00:00  GSL0003     軽油           50            100  5000
22                  NaN      NaN    NaN          NaN            NaN     0

## メタデータの抽出と結合
- 請求書上位の情報：伝票Noや発行日、企業名や企業コードなどはメタデータと呼ばれる
- メインのデータにメタデータを結合して、1つの縦型の帳票イメージにする
- 上記のような処理をよくブロードキャストという

In [29]:
df['企業名'] = _df.iloc[2, 0]
df['企業コード'] = _df.iloc[3, 4]
df['請求書No'] = _df.iloc[2, 12]
df['発行日'] = _df.iloc[3, 12]
df['発行者'] = _df.iloc[4, 12]
df['発行者コード'] = _df.iloc[4, 13]

In [30]:
df

10,日付,商品コード,品名,数量[L] or [-],単価[¥/L] or [¥],金額,企業名,企業コード,請求書No,発行日,発行者,発行者コード
11,2020-10-04 00:00:00,GSL0001,レギュラー,20,120,2400,TTT Inc.,6,012,2020/10/31,岸辺,2.0
12,2020-10-05 00:00:00,GSL0002,ハイオク,45,160,7200,TTT Inc.,6,012,2020/10/31,岸辺,2.0
13,2020-10-06 00:00:00,GSL0003,軽油,50,100,5000,TTT Inc.,6,012,2020/10/31,岸辺,2.0
14,2020-10-07 00:00:00,GSL0002,ハイオク,45,160,7200,TTT Inc.,6,012,2020/10/31,岸辺,2.0
15,2020-10-08 00:00:00,GSL0003,軽油,50,100,5000,TTT Inc.,6,012,2020/10/31,岸辺,2.0
16,2020-10-09 00:00:00,CMT0002,洗車 B,1,1500,1500,TTT Inc.,6,012,2020/10/31,岸辺,2.0
17,2020-10-10 00:00:00,GSL0003,軽油,50,100,5000,TTT Inc.,6,012,2020/10/31,岸辺,2.0
18,2020-10-11 00:00:00,GSL0002,ハイオク,40,160,6400,TTT Inc.,6,012,2020/10/31,岸辺,2.0
19,2020-10-12 00:00:00,GSL0002,ハイオク,30,160,4800,TTT Inc.,6,012,2020/10/31,岸辺,2.0
20,2020-10-13 00:00:00,GSL0003,軽油,50,100,5000,TTT Inc.,6,012,2020/10/31,岸辺,2.0
21,2020-10-14 00:00:00,GSL0003,軽油,50,100,5000,TTT Inc.,6,012,2020/10/31,岸辺,2.0
22,NaN,NaN,NaN,NaN,NaN,0,TTT Inc.,6,012,2020/10/31,岸辺,2.0

## 関数化
1. Excelを読み込む
2. カラムを取り出す
3. メインデータの抽出
4. カラム名の再定義
5. メタ情報の追加

In [31]:
def extract(filepath):
    _df = pd.read_excel(filepath)
    columns = _df.iloc[10, [1, 2, 4, 10, 11, 14]]
    df = _df.iloc[11:23, [1, 2, 4, 10, 11, 14]]
    df.columns = columns
    df['企業名'] = _df.iloc[2, 0]
    df['企業コード'] = _df.iloc[3, 4]
    df['請求書No'] = _df.iloc[2, 12]
    df['発行日'] = _df.iloc[3, 12]
    df['発行者'] = _df.iloc[4, 12]
    df['発行者コード'] = _df.iloc[4, 13]
    return df

In [37]:
df = extract(filepath)
df.head()

10,日付,商品コード,品名,数量[L] or [-],単価[¥/L] or [¥],金額,企業名,企業コード,請求書No,発行日,発行者,発行者コード
11,2020-10-04 00:00:00,GSL0001,レギュラー,20,120,2400,TTT Inc.,6,012,2020/10/31,岸辺,2.0
12,2020-10-05 00:00:00,GSL0002,ハイオク,45,160,7200,TTT Inc.,6,012,2020/10/31,岸辺,2.0
13,2020-10-06 00:00:00,GSL0003,軽油,50,100,5000,TTT Inc.,6,012,2020/10/31,岸辺,2.0
14,2020-10-07 00:00:00,GSL0002,ハイオク,45,160,7200,TTT Inc.,6,012,2020/10/31,岸辺,2.0
15,2020-10-08 00:00:00,GSL0003,軽油,50,100,5000,TTT Inc.,6,012,2020/10/31,岸辺,2.0


## データの結合

In [45]:
# pd.concat([df1, df2])を使う
sample_1 = pd.DataFrame([[1,2,3], [4,5,6]])
sample_2 = pd.DataFrame([[5,6,7], [8,9,0]])
pd.concat([sample_1, sample_2])

   0  1  2
0  1  2  3
1  4  5  6
0  5  6  7
1  8  9  0

In [46]:
pd.concat([sample_1, sample_2], axis=1)

   0  1  2  0  1  2
0  1  2  3  5  6  7
1  4  5  6  8  9  0

In [50]:
df = pd.DataFrame()

for filepath in filepaths:
    _df = extract(filepath)
    df = pd.concat([df, _df])
    
df.dropna(inplace=True)

## カラム名の並び替え

In [53]:
df = df.iloc[:, [6,7,8,9,10,0,1,2,3,4,5]]

In [55]:
df.head()

10,企業名,企業コード,請求書No,発行日,発行者,日付,商品コード,品名,数量[L] or [-],単価[¥/L] or [¥],金額
11,TTT Inc.,6,012,2020/10/31,岸辺,2020-10-04 00:00:00,GSL0001,レギュラー,20,120,2400
12,TTT Inc.,6,012,2020/10/31,岸辺,2020-10-05 00:00:00,GSL0002,ハイオク,45,160,7200
13,TTT Inc.,6,012,2020/10/31,岸辺,2020-10-06 00:00:00,GSL0003,軽油,50,100,5000
14,TTT Inc.,6,012,2020/10/31,岸辺,2020-10-07 00:00:00,GSL0002,ハイオク,45,160,7200
15,TTT Inc.,6,012,2020/10/31,岸辺,2020-10-08 00:00:00,GSL0003,軽油,50,100,5000

In [56]:
df.to_excel('output/all_data.xlsx', index=True)